describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.contains('AC').click()
    cy.contains('2').click()
    cy.contains('%').click()
    cy.contains('x').click()
    cy.contains('1').click()
    cy.contains('0').click()
    cy.contains('=').click()
    cy.get('.component-display').first().should('have.text', '0.2')
  })

  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.contains('AC').click()
    cy.contains('5').click()
    cy.contains('%').click()
    cy.contains('x').click()
    cy.contains('2').click()
    cy.contains('3').click()
    cy.contains('8').click()
    cy.contains('=').click()
    cy.get('.component-display').first().should('have.text', '11.9')
  })

  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.contains('AC').click()
    cy.contains('5').click()
    cy.contains('.').click()
    cy.contains('9').click()
    cy.contains('%').click()
    cy.contains('x').click()
    cy.contains('3').click()
    cy.contains('.').click()
    cy.contains('6').click()
    cy.contains('=').click()
    cy.get('.component-display').first().should('have.text', '0.2124')
  })
})
//EMPIEZAN LOS CAMBIOS